services:
  backend:
    image: zeeyeon/board:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/healthy" ]
      interval: 30s
      timeout: 10s
      retries: 3