server:
  port: 8080

spring:
  application:
    name: board_project

  data:
    mongodb:
      uri: mongodb://mongo:27017/board

    redis:
      host: redis
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  security:
    enabled: false

jwt:
  secretKey: "hciweieisjksdkjxnsdksdsflccslhfsdkhdshkjcshkcsjksdjfk"
  access-token-expiration: 1800
  refresh-token-expiration: 604800000